### ISSUE TITLE
Home app appears as the white screen for iOS

### ISSUE THREAD

**Issue by elinapeshelee** [winniepukki/trinat#44]
**Describe the bug**
After adding the webpage to the home screen it appears as the white screen instead of the actual application.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the website / amplify `main` branch using the iOS device
2. Add it to the home screen
3. Open the Trinat label
4. See the white screen

**Expected behaviour**
The actual application should open instead of the white screen

**Additional context**
This might be the result of the background color set to white in the #43 PR

**Comment by winniepukki** [comment]
Fixed in #43
