### ISSUE TITLE
COVID-19 notice is missing from the Web application

### ISSUE THREAD

**Issue by elinapeshelee** [winniepukki/trinat#56]
**Describe the bug**
Since the restaurant is closely related to catering, working with people face to face and offering the dine-in, dine-out services it is vital to supplement the page with the COVID-19 notice on the distance and hygiene

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Web application
2. See no COVID-19 notice has been provided

**Expected behaviour**
A clear notice on actions to prevent people from contact and the importance of COVID-19 must be provided

**Additional context**
The notice must also lead to the official governmental website, explaining the COVID-19 importance

**Comment by winniepukki** [comment]
This currently is not a must have functionality. Removing from the release to avoid confusion

**Comment by winniepukki** [comment]
Closed, as such ideas must be moved to the discussions section from now on.
